name: Git_Test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: make install
      
    - name: lint
      run: make lint

    - name: test
      run: make test

    - name: publish code coverage to code-climate (duh)
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: {{ secrets.CC_TEST_REPORTER_ID }}
      with:
        debug: true
      if: ${{ github.event_name == 'push' }}
